### ISSUE TITLE
Cannot pair and connect to my Heart rate device?

### ISSUE THREAD

**Issue by KawtharE** [kirk-quinbar/HeartRateLE#9]
Hello, 
First i would like to thank you a lot for sharing with us this example in such random subject, we really appreciate that.

Now i have a question, is this plugin suppose to work with all types of Heart rate devices?
I am trying to test the example with different devices, i am able to find all my devices in scan result always but when it comes to pairing, i can pair my smart watch but not my other heart rate device that i am suppose the receive data from it. I always get failed as result of pairing request.

Some informations about the device:
-Activation time 60sec
-BLE  version 4.x 

The Windows version is: Windows 10 Pro 1803

I really appreciate if guide me through the reasons of not being able to pair to my device.

**Comment by kirk-quinbar** [comment]
thanks for checking out my code. it was fun and interesting getting this to work. part of the problem at first was windows had horrible support for BLE devices prior to Fall 2018 Creator's edition. It looks like you are past that since that was version was 1709 and you are on 1803. I wrote this for a project i was asked to do where the device is made by Polar. Its one of those bands you wear around your chest and this all works as expected. I found out that devices might be different in their implementation of the BLE standard and some seem to work better with microsoft's BLE api than others. 

One thing to try would be to download the UWP samples from microsoft and try out their bluetooth LE example here. That gives a similar interface as mine. if it works, there might be something they are doing in their code that i am not in mine. In general i believe i am just letting windows itself do the pairing if i recall correctly by just calling their pairing api. There are a couple of different ways of pairing and i think i was just calling windows own pairing code as opposed to writing my own with their api.
https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BluetoothLE

some other things to note i ran across during my tesitng
- if you have an older computer, it might be that your computer or bluetooth interface does not support BLE or doesnt support it completely. I ran into that with one of my desktop computers and ended up having to do most of my development on my laptop.
- can you pair the device directly using the main windows bluetooth dialog. if not, then maybe windows itself doesnt understand how to connect to it? I ran into this prior to the Fall 2018 Creators edition, but unless they broke something in later versions, like yours, i wouldnt think that would be an issue anymore. lol I do recall them fixing something prior to 1709 to support ble devices, then breaking it the next release, then fixing it again for 1709 so that's microsoft for you.

**Comment by KawtharE** [comment]
@kirk-quinbar  Thank you for rapid response.
Actually i am able to pair my device with the windows system.
Could the problem be that the activation time of my device is just 60sec? or is there some sepecific hard can cause this problem and not be able to interact well with this code?

**Comment by kirk-quinbar** [comment]
woops sorry for delay. i meant to respond earlier..

yes it is very possible that specific hardware or even the ble device itself is not fully compliant which would make it so the code would not work. that is the problem, at least when i was developing this code. i found that microsoft's ble api, the ble devices and ble interfaces all have their own standards they follow and that they dont necessarily implement all the official standards. it was very frustrating, especially when microsoft's api changed 3 or 4 times and every other time broke something every time a new release of windows came out.

if things are working correctly, it should never take 60 seconds either.  that's a huge connect time. it should be pretty much instantaneous. did you try the bluetoothLE sample i listed above and did it take 60 seconds too?
